//GET
export const REQUEST_ARTICLES           = "REQUEST_ARTICLES";
export const REQUEST_ARTICLES_SUCCESS   = "REQUEST_ARTICLES_SUCCESS";
export const REQUEST_ARTICLES_ERROR     = "REQUEST_ARTICLES_ERROR";
//ADD
export const REQUEST_ADD_ARTICLE            = "REQUEST_ADD_ARTICLE";
export const REQUEST_ADD_ARTICLE_SUCCESS    = "REQUEST_ADD_ARTICLE_SUCCESS";
export const REQUEST_ADD_ARTICLE_ERROR      = "REQUEST_ADD_ARTICLE_ERROR";

